Web/Hotel.Web/Controllers/FitnessController.cs
namespace Hotel.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class FitnessController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web/Hotel.Web/Controllers/HomeController.cs
namespace Hotel.Web.Controllers
{
    using System.Diagnostics;

    using ViewModels;

    using Microsoft.AspNetCore.Mvc;

    public class HomeController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/Hotel.Web/Controllers/RestaurantController.cs
namespace Hotel.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Common;
    using Hotel.Data.Common.Repositories;
    using Data.Models;
    using Hotel.Services.Data.Restaurant;
    using Hotel.Services.Data.User;
    using ViewModels.InputModels.Restaurant;
    using ViewModels.Restaurant;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class RestaurantController : Controller
    {
        private readonly IUsersService usersService;
        private readonly IRestaurantService restaurantService;

        public RestaurantController(IUsersService usersService, IRestaurantService restaurantService)
        {
            this.usersService = usersService;
            this.restaurantService = restaurantService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Reserve()
        {
            var inputModel = new RestaurantInputModel
            {
                PhoneNumber = await usersService.GetUserPhoneNumberAsync(User),
                EventDate = DateTime.Now,
            };

            return View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Reserve(RestaurantInputModel input)
        {
            var remainingCapacity = restaurantService.GetRemainingCapacity();

            if (!ModelState.IsValid)
            {
                return View(input);
            }

            var userId = await usersService.GetUserIdAsync(User);

            input.UserId = userId;

            var result = await restaurantService.ReserveRestaurant(input);

            if (result == false)
            {
                ModelState.AddModelError("EventDate", GlobalConstants.FreeSeatsForRestaurantError + remainingCapacity);
                return View(input);
            }

            TempData["InfoMessage"] = GlobalConstants.ReserveRestaurantTempDataSuccess;

            return Redirect("/Restaurant/Reservations");
        }

        [HttpGet]
        public async Task<IActionResult> Reservations()
        {
            var userId = await usersService.GetUserIdAsync(User);

            var reservations = await restaurantService
                .GetAllReservationsAsync<RestaurantAllViewModel>(userId);

            var reservationView = new RestaurantViewModel()
            {
                AllReservations = reservations,
            };

            return View(reservationView);
        }
    }
}

Web/Hotel.Web/Controllers/RoomController.cs
namespace Hotel.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Common;
    using Hotel.Data.Common.Repositories;
    using Data.Models;
    using Hotel.Services.Data.Room;
    using Hotel.Services.Data.User;
    using ViewModels.InputModels.Room;
    using ViewModels.RoomViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    public class RoomController : Controller
    {
        private readonly IRoomsService roomsService;
        private readonly IUsersService usersService;
        private readonly IDeletableEntityRepository<Picture> picturesRepository;

        public RoomController(
            IRoomsService roomsService,
            IUsersService usersService,
            IDeletableEntityRepository<Picture> picturesRepository)
        {
            this.roomsService = roomsService;
            this.usersService = usersService;
            this.picturesRepository = picturesRepository;
        }
        [HttpGet]
        public async Task<IActionResult> All()
        {
            var rooms = await roomsService
                .GetAllRoomsAsync<RoomsAllViewModel>();

            var roomView = new RoomViewModel()
            {
                AllRooms = rooms,
            };

            return View(roomView);
        }

        [HttpGet]
        [Route("Room/Details/{roomId}")]
        public async Task<IActionResult> Details([FromRoute] string roomId)
        {
            var room = await roomsService.GetRoomAsync<RoomDetailsViewModel>(roomId);

            return View(room);
        }

        [Authorize]
        [HttpGet]
        [Route("Room/Reserve/{roomId}")]
        public async Task<IActionResult> Reserve([FromRoute] string roomId)
        {
            var inputModel = new ReserveRoomInputModel();

            var pictures = await picturesRepository.All().Where(x => x.RoomId == roomId).ToListAsync();

            inputModel.Pictures = pictures.Select(x => x.Url).ToList();
            inputModel.PhoneNumber = await usersService.GetUserPhoneNumberAsync(User);
            inputModel.CheckIn = DateTime.Now;
            inputModel.CheckOut = DateTime.Now;

            return View(inputModel);
        }

        [HttpPost]
        [Route("Room/Reserve/{roomId}")]
        public async Task<IActionResult> Reserve([FromRoute] string roomId, ReserveRoomInputModel input)
        {
            var pictures = await picturesRepository.All().Where(x => x.RoomId == roomId).ToListAsync();
            var room = roomsService.GetRoomById(roomId);

            if (!ModelState.IsValid || room.NumberOfBeds < input.CountOfPeople)
            {
                ModelState.AddModelError("CountOfPeople", GlobalConstants.EnterValidNumberOfGuestsError + room.NumberOfBeds);
                input.Pictures = pictures.Select(x => x.Url).ToList();
                return View(input);
            }

            var userId = await usersService.GetUserIdAsync(User);

            input.UserId = userId;
            input.RoomId = roomId;

            var result = await roomsService.ReserveRoom(input);

            if (result == false)
            {
                ModelState.AddModelError("NumberOfNights", GlobalConstants.EnterAtleastOneNightStandsError);
                input.Pictures = pictures.Select(x => x.Url).ToList();
                return View(input);
            }

            TempData["InfoMessage"] = GlobalConstants.ReserveRoomTempDataSuccess;

            return Redirect("/Room/Reservations");
        }

        [HttpGet]
        public async Task<IActionResult> Reservations()
        {
            var userId = await usersService.GetUserIdAsync(User);

            var reservations = await roomsService
                .GetAllReservationsAsync<ReservationsAllViewModel>(userId);

            var reservationView = new ReservationViewModel()
            {
                AllReservations = reservations,
            };

            return View(reservationView);
        }
    }
}

Web/Hotel.Web/Controllers/SpaController.cs
namespace Hotel.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class SpaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web/Hotel.Web/Views/Home/Index.cshtml
@using Hotel.Common
@{
    ViewData["Title"] = "Home Page";
}



<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-caption">
          <p>Where dreams are born!</p>
        </div>
        <div class="carousel-item active">
            <img class="d-block w-100" src="https://res.cloudinary.com/dp73jqinw/image/upload/v1609148961/Santorini_Hotels_Best_View_Sea_Caldera_Volcano_-_Home_rkb7ul.jpg" height="500" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://res.cloudinary.com/dp73jqinw/image/upload/v1609149227/miamb-outdoor-pool-1969-hor-feat_gfuruo.jpg" height="500" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://res.cloudinary.com/dp73jqinw/image/upload/v1609149465/fllsb-view-0077-hor-feat_nwpqdk.jpg" height="500" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

@*<div class="text-center">
    <br/>
    <h2>Rooms</h2>
    <br/>
</div>*@

<div class="jumbotron">
    <div class="container text-center">
        <h1 class="display-4">Rooms</h1>
        <p class="lead">We have all that you will ever need and more.</p>
    </div>
</div>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="/images/singleRoom.jpg" width="70" height="550" alt="First slide">
            <h5>Single room</h5>
            <p>We got the perfect single room for your absolute comfort.</p>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="/images/doubleRoom2.jpg" width="115" height="500" alt="Second slide">
            <h5>Double room</h5>
            <p>Double room for your comfort when sharing.</p>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="/images/suite1.jpg" width="100" height="550" alt="Third slide">
            <h5>Apartment</h5>
            <p>We got you covered with the most luxurious apartments you can imagine.</p>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<a class="btn btn-secondary btn-lg btn-block" asp-area="" asp-controller="Room" asp-action="All">Make your reservation now</a>

<div class="jumbotron">
    <div class="container text-center">
        <h1 class="display-4">Facilities</h1>
        <p class="lead">From fine cuisine to total relaxation we got you covered!</p>
    </div>

</div>
<div class="card-group">
    <div class="card">
        <img class="card-img-top" src="/images/category2.png" height="250" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Restaurant</h5>
            <p class="card-text">Get ready to for the most exquisite cuisine you have ever tasted!</p>
            <a class="btn btn-secondary" asp-area="" asp-controller="Restaurant" asp-action="Index">Make your reservation</a>
        </div>
    </div>
    <div class="card">
        <img class="card-img-top" src="/images/spa3.jpg" height="250" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Spa</h5>
            <p class="card-text">Pleasure and relaxation like no other!</p>
            <a class="btn btn-secondary" asp-area="" asp-controller="Spa" asp-action="Index">Spa</a>
            
        </div>
    </div>
    <div class="card">
        <img class="card-img-top" src="/images/fitness1.jpg" height="250" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Fitness center</h5>
            <p class="card-text">Do your training in the comfort of your stay!</p>
            <a class="btn btn-secondary" asp-area="" asp-controller="Fitness" asp-action="Index">Fitness</a>
        </div>
    </div>
</div>

<div class="jumbotron">
    <div class="container text-center">
        <h1 class="display-4">Event Halls</h1>
        <p class="lead">From work to pleasure we got you all the way!</p>
    </div>
</div>

<div class="card-group">
    <div class="card">
        <img class="card-img-top" src="/images/conf.jpg" height="250" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Conference Hall</h5>
            <p class="card-text">You got a team-building and need a business meeting, we got that for you!</p>
        </div>
    </div>
    <div class="card">
        <img class="card-img-top" src="/images/gala2.jpg" height="250" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Galla Hall</h5>
            <p class="card-text">Our Galla hall will satisfy every caprice your boss may have for your team-building!</p>
        </div>
    </div>
    <div class="card">
        <img class="card-img-top" src="/images/sports.jpg" height="250" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Sport Hall</h5>
            <p class="card-text">You can gather and play various of sports in our sports hall!</p>
        </div>
    </div>
</div>

<a class="btn btn-secondary btn-lg btn-block" asp-area="" asp-controller="ConferenceHall" asp-action="Reserve">Make your reservation now</a>
<br/>
<script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
<script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>