Web/Hotel.Web/Controllers/ContactController.cs
namespace Hotel.Web.Controllers
{
    using System.Threading.Tasks;

    using Common;
    using ViewModels.InputModels.Contact;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Configuration;
    using SendGrid;
    using SendGrid.Helpers.Mail;

    public class ContactController : Controller
    {
        private readonly IConfiguration configuration;

        public ContactController(IConfiguration configuration)
        {
            this.configuration = configuration;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var apiKey = configuration.GetValue<string>("ExternalProviders:SendGrid:ApiKey");

            var client = new SendGridClient(apiKey);
            var name = model.FirstName + " " + model.LastName;
            var from = new EmailAddress(model.Email, name);
            var subject = model.Title;
            var to = new EmailAddress("dimitarkrustanov@gmail.com", "Hotel");
            var plainTextContent = model.Content;
            var htmlContent = $"<p>{model.Content}</p>";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);

            await client.SendEmailAsync(msg);

            TempData["InfoMessage"] = GlobalConstants.SuccessfullySentAnEmail;

            return Redirect("/");
        }
    }
}

Web/Hotel.Web/Controllers/FitnessController.cs
namespace Hotel.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class FitnessController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web/Hotel.Web/Controllers/RoomController.cs
namespace Hotel.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Common;
    using Hotel.Data.Common.Repositories;
    using Data.Models;
    using Hotel.Services.Data.Room;
    using Hotel.Services.Data.User;
    using ViewModels.InputModels.Room;
    using ViewModels.RoomViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    public class RoomController : Controller
    {
        private readonly IRoomsService roomsService;
        private readonly IUsersService usersService;
        private readonly IDeletableEntityRepository<Picture> picturesRepository;

        public RoomController(
            IRoomsService roomsService,
            IUsersService usersService,
            IDeletableEntityRepository<Picture> picturesRepository)
        {
            this.roomsService = roomsService;
            this.usersService = usersService;
            this.picturesRepository = picturesRepository;
        }
        [HttpGet]
        public async Task<IActionResult> All()
        {
            var rooms = await roomsService
                .GetAllRoomsAsync<RoomsAllViewModel>();

            var roomView = new RoomViewModel()
            {
                AllRooms = rooms,
            };

            return View(roomView);
        }

        [HttpGet]
        [Route("Room/Details/{roomId}")]
        public async Task<IActionResult> Details([FromRoute] string roomId)
        {
            var room = await roomsService.GetRoomAsync<RoomDetailsViewModel>(roomId);

            return View(room);
        }

        [Authorize]
        [HttpGet]
        [Route("Room/Reserve/{roomId}")]
        public async Task<IActionResult> Reserve([FromRoute] string roomId)
        {
            var inputModel = new ReserveRoomInputModel();

            var pictures = await picturesRepository.All().Where(x => x.RoomId == roomId).ToListAsync();

            inputModel.Pictures = pictures.Select(x => x.Url).ToList();
            inputModel.PhoneNumber = await usersService.GetUserPhoneNumberAsync(User);
            inputModel.CheckIn = DateTime.Now;
            inputModel.CheckOut = DateTime.Now;

            return View(inputModel);
        }

        [HttpPost]
        [Route("Room/Reserve/{roomId}")]
        public async Task<IActionResult> Reserve([FromRoute] string roomId, ReserveRoomInputModel input)
        {
            var pictures = await picturesRepository.All().Where(x => x.RoomId == roomId).ToListAsync();
            var room = roomsService.GetRoomById(roomId);

            if (!ModelState.IsValid || room.NumberOfBeds < input.CountOfPeople)
            {
                ModelState.AddModelError("CountOfPeople", GlobalConstants.EnterValidNumberOfGuestsError + room.NumberOfBeds);
                input.Pictures = pictures.Select(x => x.Url).ToList();
                return View(input);
            }

            var userId = await usersService.GetUserIdAsync(User);

            input.UserId = userId;
            input.RoomId = roomId;

            var result = await roomsService.ReserveRoom(input);

            if (result == false)
            {
                ModelState.AddModelError("NumberOfNights", GlobalConstants.EnterAtleastOneNightStandsError);
                input.Pictures = pictures.Select(x => x.Url).ToList();
                return View(input);
            }

            TempData["InfoMessage"] = GlobalConstants.ReserveRoomTempDataSuccess;

            return Redirect("/Room/Reservations");
        }

        [HttpGet]
        public async Task<IActionResult> Reservations()
        {
            var userId = await usersService.GetUserIdAsync(User);

            var reservations = await roomsService
                .GetAllReservationsAsync<ReservationsAllViewModel>(userId);

            var reservationView = new ReservationViewModel()
            {
                AllReservations = reservations,
            };

            return View(reservationView);
        }
    }
}

Web/Hotel.Web/Controllers/SpaController.cs
namespace Hotel.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class SpaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web/Hotel.Web/Views/Shared/_Layout.cshtml
@using Hotel.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @GlobalConstants.SystemName</title>
    <environment names="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/lazy.css">
    </environment>
    <environment names="Staging,Production">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/lazy.css">
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light">
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navigations-02" aria-expanded="false" style=""><span class="navbar-toggler-icon"></span></button>
            <div class="navbar-collapse justify-content-md-center collapse" id="navigations-02" style="">
                <div class="row w-100">
                    <div class="col-4 pl-lg-0">
                        <ul class="navbar-nav">
                            <li class="nav-item"><a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home<span class="sr-only">(current)</span></a></li>
                            <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Room" asp-action="All">Rooms</a></li>
                            <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Room" asp-action="All">Reserve</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller="Restaurant" asp-action="Index">Restaurant</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller="Contact" asp-action="Index">Contacts</a></li>
                        </ul>
                    </div>
                    <div class="col-4 navbar-nav text-center pr-0 d-none d-lg-block"><a class="navbar-brand mr-0" href="#">Hotel</a></div>
                    <div class="col-4 pr-lg-0">
                        <ul class="navbar-nav justify-content-end">
                            <div class="dropdown">
                                <button type="button" class="btn text-dark dropdown-toggle" data-toggle="dropdown">
                                   Facilities
                                </button>
                                <div class="dropdown-menu">
                                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Spa" asp-action="Index">Spa</a></li>
                                    <li class="nav-item"><a class="nav-link" asp-controller="ConferenceHall" asp-action="Index">Events Hall</a></li>
                                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Fitness" asp-action="Index">Fitness</a></li>
                                </div>
                            </div>
                            <li class="nav-item"><partial name="_LoginPartial"/></li>

                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center p-2" style="background-color:ghostwhite">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/lazy.js" asp-append-version="true"></script>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/lazy.js" asp-append-version="true"></script>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    </environment>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/Hotel.Web/Views/Shared/_StatusMessages.cshtml
<div class="container">
</div>