Web/Hotel.Web/Areas/Administration/Controllers/ReservationsController.cs
using System.Threading.Tasks;
using Hotel.Services.Data.ConferenceHall;
using Hotel.Services.Data.Restaurant;
using Hotel.Services.Data.Room;
using Hotel.Web.ViewModels.ConferenceHall;
using Hotel.Web.ViewModels.Restaurant;
using Hotel.Web.ViewModels.RoomViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Hotel.Web.Areas.Administration.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly IRestaurantService restaurantService;
        private readonly IConferenceHallService conferenceHallService;
        private readonly IRoomsService roomsService;

        public ReservationsController(
            IRestaurantService restaurantService,
            IConferenceHallService conferenceHallService,
            IRoomsService roomsService)
        {
            this.restaurantService = restaurantService;
            this.conferenceHallService = conferenceHallService;
            this.roomsService = roomsService;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> AllRoomReservations()
        {
            var reservations = await this.roomsService
                .GetAllReservationsAsyncForAdmin<ReservationsAllViewModel>();

            var reservationView = new ReservationViewModel()
            {
                AllReservations = reservations,
            };

            return this.View("~/Views/Room/Reservations.cshtml", reservationView);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> AllRestaurantReservations()
        {
            var reservations = await this.restaurantService
                .GetAllReservationsAsyncForAdmin<RestaurantAllViewModel>();

            var reservationView = new RestaurantViewModel()
            {
                AllReservations = reservations,
            };

            return this.View("~/Views/Restaurant/Reservations.cshtml", reservationView);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> AllConferenceHallReservations()
        {
            var reservations = await this.conferenceHallService
                 .GetAllReservationsAsyncForAdmin<ConfHallAllViewModel>();

            var reservationView = new ConfHallViewModel()
            {
                AllReservations = reservations,
            };

            return this.View("~/Views/ConferenceHall/Reservations.cshtml", reservationView);
        }
    }
}

Web/Hotel.Web/Controllers/ConferenceHallController.cs
namespace Hotel.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Common;
    using Hotel.Services.Data.ConferenceHall;
    using Hotel.Services.Data.User;
    using ViewModels.ConferenceHall;
    using ViewModels.InputModels.ConferenceHall;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class ConferenceHallController : Controller
    {
        private readonly IConferenceHallService conferenceHallService;
        private readonly IUsersService usersService;

        public ConferenceHallController(IConferenceHallService conferenceHallService, IUsersService usersService)
        {
            this.conferenceHallService = conferenceHallService;
            this.usersService = usersService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Reserve()
        {
            var inputModel = new ConferenceHallInputModel
            {
                PhoneNumber = await usersService.GetUserPhoneNumberAsync(User),
                EventDate = DateTime.Now,
            };

            return View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Reserve(ConferenceHallInputModel input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }

            var userId = await usersService.GetUserIdAsync(User);

            input.UserId = userId;

            var result = await conferenceHallService.ReserveConferenceHall(input);

            var capacity = await conferenceHallService
                .GetAllHallsAsync<ConfHallAllViewModel>(input);

            if (result == false)
            {
                ModelState.AddModelError("EventDate", GlobalConstants.FreeSeatsForHallError + capacity);
                return View(input);
            }

            TempData["InfoMessage"] = GlobalConstants.ReserveConferenceHallTempDataSuccess;

            return Redirect("/ConferenceHall/Reservations");
        }

        [HttpGet]
        public async Task<IActionResult> Reservations()
        {
            var userId = await usersService.GetUserIdAsync(User);

            var reservations = await conferenceHallService
                .GetAllReservationsAsync<ConfHallAllViewModel>(userId);

            var reservationView = new ConfHallViewModel()
            {
                AllReservations = reservations,
            };

            return View(reservationView);
        }
    }
}

Web/Hotel.Web/Views/ConferenceHall/Index.cshtml
@{
    ViewData["Title"] = "Event Halls";
}

<div id="conferenceHall" class="container">
    <div class="row">
        <div id="hallImgSlider" class="col-lg-12">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="https://images.pexels.com/photos/1181396/pexels-photo-1181396.jpeg" width="100%">
                    </div>
                    <div class="carousel-item">
                        <img src="https://high5test.com/wp-content/uploads/2019/10/team-building-techniques-1024x670.jpeg" width="100%">
                    </div>
                    <div class="carousel-item">
                        <img src="https://smart-space.co.uk/content/gallery/steel/stcou8-02/kingsbury-sports-hall-stcou8-0.jpg" width="100%">
                    </div>
                    <div class="carousel-item">
                        <img src="https://www.swissdigitalhealth.com/wp-content/uploads/2017/03/conference-showcase-SDH.jpg" width="134%" />
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>

    <div id="hallDescription" class="row" align="center">
        <div class="col-lg-12">
            <p>The Hotel have all the event halls that you may need.
                Choosing our event halls you make sure that you are covered for everything like:</p>
            <li>Conference</li>
            <li>Team build</li>
            <li>Sports event</li>
            <li>Business meeting</li>
            <br/>
            <p>We are going to help you make your event unforgettable and to enjoy it to the fullest!</p>
            <p>We are awaiting you!</p>
            <a class="btn btn-outline-dark" asp-area="" asp-controller="ConferenceHall" asp-action="Reserve">Reserve</a>
        </div>
    </div>
</div>  

Web/Hotel.Web/Views/ConferenceHall/Reservations.cshtml
@using Hotel.Common
@model Hotel.Web.ViewModels.ConferenceHall.ConfHallViewModel
@{
    ViewData["Title"] = "Reserved Event Halls";
}

<script>
        var msg = '@TempData["InfoMessage"]';
            if (msg.length) {
            alert(msg);
        }
</script>

@if (Model.AllReservations == null || !Model.AllReservations.Any())
{
@if (User.IsInRole(GlobalConstants.AdministratorRoleName))
    {
<div class="col-lg-12 text-center">
    <h2>Currently there is no active reservations</h2>
    <a class="btn btn-outline-warning" href="/Identity/Account/Manage">Go back</a>
</div>
    }
    else
    {
<div class="col-lg-12 text-center">
    <h2>Currently there is no active reservations</h2>
    <a class="btn btn-outline-warning" href="/Identity/Account/Manage">Go back</a>
</div>
    }
}
else
{
@if (User.IsInRole(GlobalConstants.AdministratorRoleName))
    {
<div class="col-lg-12 text-center">
    <h2>Event Halss reservations <a class="btn btn-outline-warning" href="/Identity/Account/Manage">Go back</a></h2>
</div>
    }
    else
    {
<div class="col-lg-12 text-center">
    <h2>My reservations <a class="btn btn-outline-warning" href="/Identity/Account/Manage">Go back</a></h2>
</div>
    }
<div class="row">
    <div class="col-lg-12">
        <table class="table table-striped table-borderless">
            <thead>
                <tr>
                    <th scope="col">First name</th>
                    <th scope="col">Surname</th>
                    <th scope="col">Phone number</th>
                    <th scope="col">Type of the event</th>
                    <th scope="col">Guests</th>
                    <th scope="col">Date</th>
                    <th scope="col">From</th>
                    <th scope="col">To</th>
                    <th scope="col">Price</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.AllReservations)
                    {
                        var eventType = "";

                        if (item.EventType == "Conference")
                        {
                            eventType = "Conference";
                        }
                        if (item.EventType == "TeamBuilding")
                        {
                            eventType = "Team Building";
                        }
                        if (item.EventType == "Sports")
                        {
                            eventType = "Sports";
                        }
                        if (item.EventType == "BusinessMeeting")
                        {
                            eventType = "Business Meeting";
                        }
                <tr>
                    <td>@item.User.FirstName</td>
                    <td>@item.User.LastName</td>
                    <td>@item.PhoneNumber</td>
                    <td>@eventType</td>
                    <td>@item.NumberOfGuests</td>
                    <td>@item.EventDate.ToString("dd/MM/yyyy")</td>
                    <td>@item.CheckIn.ToString("hh:mm tt")</td>
                    <td>@item.CheckOut.ToString("hh:mm tt")</td>
                    <td>@item.TotalPrice bgn.</td>
                </tr>
                    }
            </tbody>
        </table>
    </div>
</div>
}

Web/Hotel.Web/Views/ConferenceHall/Reserve.cshtml
@using Microsoft.AspNetCore.Identity
@using Hotel.Data.Models
@{
    ViewData["Title"] = "Reservations for halls";
}

@inject SignInManager<ApplicationUser> SignInManager
@model Hotel.Web.ViewModels.InputModels.ConferenceHall.ConferenceHallInputModel
<section id="conferenceHallReserveForm">
    <div class="container">
        <div id="reserveHeader" class="d-flex justify-content-center">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Reserve a hall</h2>

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-5">
                <form asp-controller="ConferenceHall" asp-action="Reserve">
                    <div class="form-group">
                        <i class="fa fa-user icon"></i>
                        <select class="form-control" asp-for="EventType">
                            <option value="1">Conference</option>
                            <option value="2">Team building</option>
                            <option value="3">Sport</option>
                            <option value="4">Business meeting</option>
                        </select>
                    </div>
                    <span asp-validation-for="EventType" class="text-danger"></span>

                    <div class="form-group">
                        <i class="fa fa-envelope icon"></i>
                        <input class="form-control" asp-for="EmailAddress" value="@User.Identity.Name" placeholder="E-mail">
                    </div>
                    <span asp-validation-for="EmailAddress" class="text-danger"></span>

                    <div class="form-group">
                        <i class="fa fa-phone icon"></i>
                        <input class="form-control" asp-for="PhoneNumber" placeholder="Phone number">
                    </div>
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>

                    <div class="form-group">
                        <i class="fa fa-group icon"></i>
                        <input class="form-control" asp-for="NumberOfGuests" placeholder="Number of guests">
                    </div>
                    <span asp-validation-for="NumberOfGuests" class="text-danger"></span>

                    <div class="form-group">
                        <i class="fa fa-calendar icon"></i>
                        <input type="date" class="form-control" asp-for="EventDate" placeholder="Date of the event:">
                    </div>
                    <span asp-validation-for="EventDate" class="text-danger"></span>

                    <div class="form-group">
                        <i class="fa fa-clock-o icon"></i>
                        <input type="time" class="form-control" asp-for="CheckIn" placeholder="Starting hour:">
                    </div>
                    <span asp-validation-for="CheckIn" class="text-danger"></span>

                    <div class="form-group">
                        <i class="fa fa-clock-o icon"></i>
                        <input type="time" class="form-control" asp-for="CheckOut" placeholder="Finishing hour:">
                    </div>
                    <span asp-validation-for="CheckOut" class="text-danger"></span>

                    <div class="form-group">
                        <i class="fa fa-commenting icon"></i>
                        <textarea class="form-control" asp-for="Message" rows="3" placeholder="Your message."></textarea>
                    </div>
                    <span asp-validation-for="Message" class="text-danger"></span>

                    <input type="submit" value="Reserve" class="btn btn-outline-dark" asp-area="" asp-controller="ConferenceHall" asp-action="Reserve">


                </form>
            </div>

                </div>
            </div>
</section>